"""added tables and relationships

Revision ID: 6ff4f21310e2
Revises: 75acb1a89671
Create Date: 2025-12-30 01:55:28.563065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff4f21310e2'
down_revision: Union[str, Sequence[str], None] = '75acb1a89671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('categories', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint('unique_category_per_user', 'categories', ['name', 'owner_id'])
    op.create_foreign_key(None, 'categories', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('expenses', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'expenses', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('expenses', 'owner_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('unique_category_per_user', 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'owner_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
